### PR TITLE
adding summary information on feeds (atom and json)

### PR DESCRIPTION
**Pull request by tcelestino**
I read the usesthis.com a long time and I discovered lot of software there. 

So, I'm building on bot to read the feeds, but I've been feeling missing more informations about that interviewed. I saw there was the information (summary) and I created this PR to add these information on feeds (atom and json).

Congrats and carry on this project.

:crab:

### CODE REVIEW

**Comment by waferbaby** [comment]
Hey, awesome!

**Comment by waferbaby** [comment]
I'd love to see your bot! What's it going to do?

**Comment by tcelestino** [comment]
> I'd love to see your bot! What's it going to do?

It's a Telegram bot. 

I always open usesthis.com to read a interview and I sometimes I forget to do it. So, I'm doing a bot with commands to show the lists interviews or just the last interview. At moment the bot show only a link to interview but I wanna do make a schedule to show a notification when there's a new interview, I wanna create a instant view template, etc...

When I have finished I'll say. 

Thanks for merge! 

🦀

**Comment by waferbaby** [comment]
@tcelestino Ah, that's awesome!

**Pull request merged**
