### PR TITLE
Change my name

### PR DESCRIPTION
**Pull request by lazerwalker**
Hi! I've started going by a different name + pronouns, so I'd really appreciate if this could get updated. I don't know if other changes will be needed to accommodate a URL slug change, but figured I'd open a PR to get things started for you. Let me know if there are other ways I can help make this happen! :D

### CODE REVIEW

**Comment by waferbaby** [comment]
Woo! I'll add a redirect for the old URL, too!

**Comment by waferbaby** [comment]
Done! Did you want to use a different image, too?

**Comment by lazerwalker** [comment]
Thanks!!

And yeah, good call on the image. https://lazerwalker.com/images/me.png work for now?

**Comment by waferbaby** [comment]
@lazerwalker Yeah! Updated. Lemme know if you want me to swap in a different one whenever :)

**Pull request merged**
