### PR TITLE
WIP: Update some links and fix typo

### PR DESCRIPTION
**Pull request by hezhizhen**
Update some links and descriptions in `gear` based on current homepages. I also fix some typo in `posts`.

### CODE REVIEW

**Comment by hezhizhen** [comment]
Some URL starting with `http` are changed to `https` and all modified URLs are manually opened to check.

**Comment by hezhizhen** [comment]
I've run `./tasks/scan` and there are about 1000 changes there. Maybe I should submit them first? @waferbaby

**Review by waferbaby — APPROVED** [review]
Oh wow, this is amazing, thank you so much! <3

**Comment by waferbaby** [comment]
Happy to submit as is, happy for you to do more, but only if you want to!

**Comment by hezhizhen** [comment]
> Happy to submit as is, happy for you to do more, but only if you want to!

Okay. I'll create a PR later for `./task/scan` and after it's merged I'll update this PR.

**Comment by hezhizhen** [comment]
> > Happy to submit as is, happy for you to do more, but only if you want to!
> 
> Okay. I'll create a PR later for `./task/scan` and after it's merged I'll update this PR.

See https://github.com/waferbaby/usesthis/pull/119

**Pull request closed without merging**
